namespace NotAnAPI.ReKact.Core.Enums
{
    /// <summary>
    /// Enum ActTypes
    /// </summary>
    /// <autogeneratedoc />
    public enum ActTypes
    {
        /// <summary>
        /// The key down
        /// </summary>
        /// <autogeneratedoc />
        KeyDown = 1,
        /// <summary>
        /// The key up
        /// </summary>
        /// <autogeneratedoc />
        KeyUp = 2,
        /// <summary>
        /// The key press
        /// </summary>
        /// <autogeneratedoc />
        KeyPress = 3,
    }
}
