namespace NotAnAPI.ReKact.Core.Enums
{
    /// <summary>
    /// Enum KactValues
    /// </summary>
    /// <autogeneratedoc />
    public enum KactValues
    {
        /// <summary>
        /// The index
        /// </summary>
        /// <autogeneratedoc />
        Index = 0,
        /// <summary>
        /// The type
        /// </summary>
        /// <autogeneratedoc />
        Type = 1,
        /// <summary>
        /// The time
        /// </summary>
        /// <autogeneratedoc />
        Time = 2,
        /// <summary>
        /// The key code
        /// </summary>
        /// <autogeneratedoc />
        KeyCode = 3,
        /// <summary>
        /// The L
        /// </summary>
        /// <autogeneratedoc />
        L = 4,
        /// <summary>
        /// The modifier
        /// </summary>
        /// <autogeneratedoc />
        Modifier = 5,
        /// <summary>
        /// The form element
        /// </summary>
        /// <autogeneratedoc />
        FormElement = 6,
        /// <summary>
        /// The not trusted
        /// </summary>
        /// <autogeneratedoc />
        NotTrusted = 7,
    }
}
