namespace NotAnAPI.ReKact.Core.Enums
{
    /// <summary>
    /// Enum ReadableSources
    /// </summary>
    /// <autogeneratedoc />
    public enum ReadableSources
    {
        /// <summary>
        /// The unknown
        /// </summary>
        /// <autogeneratedoc />
        Unknown = 0,
        /// <summary>
        /// The arguments
        /// </summary>
        /// <autogeneratedoc />
        Args = 1,
        /// <summary>
        /// The clipboard
        /// </summary>
        /// <autogeneratedoc />
        Clipboard = 2,
        /// <summary>
        /// The file
        /// </summary>
        /// <autogeneratedoc />
        File = 3,
    }
}
