using System.Collections.Generic;

namespace NotAnAPI.ReKact.Core.EventArgs
{
    /// <summary>
    /// Class KeyUpEventArgs.
    /// Implements the <see cref="System.EventArgs" />
    /// </summary>
    /// <seealso cref="System.EventArgs" />
    /// <autogeneratedoc />
    public class KeyUpEventArgs : System.EventArgs
    {
        /// <summary>
        /// Gets the key act.
        /// </summary>
        /// <value>The key act.</value>
        /// <autogeneratedoc />
        public KeyAct KeyAct { get; private set; }
        /// <summary>
        /// Gets the key press queue.
        /// </summary>
        /// <value>The key press queue.</value>
        /// <autogeneratedoc />
        public List<KeyAct> KeyPressQueue { get; private set; }
        /// <summary>
        /// Gets the key up queue.
        /// </summary>
        /// <value>The key up queue.</value>
        /// <autogeneratedoc />
        public List<KeyAct> KeyUpQueue { get; private set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="KeyUpEventArgs"/> class.
        /// </summary>
        /// <param name="keyAct">The key act.</param>
        /// <param name="keyPressQueue">The key press queue.</param>
        /// <param name="keyUpQueue">The key up queue.</param>
        /// <autogeneratedoc />
        public KeyUpEventArgs(KeyAct keyAct, List<KeyAct> keyPressQueue, List<KeyAct> keyUpQueue)
        {
            this.KeyAct = keyAct;
            this.KeyPressQueue = keyPressQueue;
            this.KeyUpQueue = keyUpQueue;
        }
    }
}
