using System.Text.RegularExpressions;

namespace NotAnAPI.ReKact.Core
{
    /// <summary>
    /// Class Globals.
    /// </summary>
    /// <autogeneratedoc />
    public static class Globals
    {
        /// <summary>
        /// Class Regexes.
        /// </summary>
        /// <autogeneratedoc />
        public static class Regexes
        {
            /// <summary>
            /// The Regex used to extract kact from sensor
            /// </summary>
            public static Regex ExtractKactFromSensor = new("(-1,2,-94,-108,)(?<Kact>.*?)(-1,2,-94,-110,)");

            /// <summary>
            /// The Regex used to validate kact string
            /// </summary>
            public static Regex ValidateKactString = new(@"^[\d\,\;\-]{1,}$", RegexOptions.Singleline);
        }
    }
}
